#!/bin/bash
./hpc $1 init.py > conns$1
mv data/sim.pkl sim$1
python gather.py $1
./hpc $2 init.py > conns$2
mv data/sim.pkl sim$2
python gather.py $2
python compare.py sim$1 sim$2
python parseConns.py conns$1 conns$2
python ddiff.py secsg$1 secsg$2
